import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProviderNextTheme } from "@/utils/ThemeProvider";
import { ThemeProvider } from "./theme-provider";
import { Analytics } from "@vercel/analytics/react";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "React Tailwind",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProviderNextTheme
          attribute="class"
          defaultTheme="system"
          enableSystem={false}
        >
          <ThemeProvider>{children}</ThemeProvider>
        </ThemeProviderNextTheme>
        <Analytics />
      </body>
    </html>
  );
}
